### ISSUE TITLE
Roblox Blinded Black Screen 

### ISSUE THREAD

**Issue by basherfarro** [e666666/robloxWineBuildGuide#4] opened 2021-09-20 05:33 UTC
I can do things but Im blinded I cant see

**Comment by e666666** [comment] 2021-09-23 12:30
Sounds like something is wrong with either your graphics driver or libraries, I would suggest you to ask help on the Grapejuice Discord server (https://discord.gg/mRTzEb6), since it will be really painful to try to figure out the issue from here.
Closing this GitHub issue since not enough info was provided. Please ask for help on the Grapejuice server, good luck on finding the cause.

**Closed by e666666** 2021-09-23 12:30 UTC
